#!/bin/bash
CONF="$HOME/.config/bongocat/bongocat.conf"
POSFILE="$HOME/.config/bongocat/position"

if pgrep -f "bongocat --watch-config" > /dev/null; then
    pkill -f "bongocat --watch-config" 2>/dev/null
    pkill -f bongocat-counter 2>/dev/null
    echo "bongocat stopped"
    exit 0
fi

echo "where do you want the cat?"
echo "1) left"
echo "2) center"
echo "3) right"
read -p "choose [1-3]: " choice

case "$choice" in
    1|left|Left)
        pos="left"
        ;;
    2|center|Center|middle|Middle)
        pos="center"
        ;;
    3|right|Right)
        pos="right"
        ;;
    *)
        pos="right"
        ;;
esac

sed -i "s/^cat_align=.*/cat_align=$pos/" "$CONF"
echo "$pos" > "$POSFILE"

echo "starting bongocat on $pos"
export LD_PRELOAD=/usr/lib/libgtk4-layer-shell.so
bongocat --watch-config &
sleep 1
/home/xlrc888/.local/bin/bongocat-counter &
wait
